In [ ]:
# --- Conceptos Base: Creación y Atributos ---
import numpy as np

# Creación desde una lista
lista_py = [[1, 2, 3], [4, 5, 6]]
mi_array = np.array(lista_py)

print(f"El array:\n{mi_array}")

# --- Explicación detallada del uso (Atributos) ---
# Los atributos son variables 'dentro' del objeto (sin paréntesis)

# .shape: La forma del array (filas, columnas)
print(f"\nForma (shape): {mi_array.shape}") # (2, 3)

# .dtype: El tipo de dato (crucial para la eficiencia)
print(f"Tipo de dato (dtype): {mi_array.dtype}") # int32 o int64

# .ndim: Número de dimensiones
print(f"Dimensiones (ndim): {mi_array.ndim}") # 2 dimensiones

# .size: Número total de elementos
print(f"Total elementos (size): {mi_array.size}") # 2 * 3 = 6

El array:
[[1 2 3]
 [4 5 6]]

Forma (shape): (2, 3)
Tipo de dato (dtype): int64
Dimensiones (ndim): 2
Total elementos (size): 6


In [ ]:
# --- Conceptos Base: Generadores de Arrays ---

# np.arange(): Como el range() de Python, pero devuelve un array
# (inicio, fin_no_incluido, paso)
arr_rango = np.arange(0, 10, 2)
print(f"np.arange(0, 10, 2):\n{arr_rango}")

# np.zeros(): Crea un array de ceros. Útil para inicializar.
# Recibe una 'tupla' con la forma (filas, columnas)
arr_ceros = np.zeros((3, 4)) # 3 filas, 4 columnas
print(f"\nnp.zeros((3, 4)):\n{arr_ceros}")

# np.ones(): Igual, pero con unos.
arr_unos = np.ones((2, 3))
print(f"\nnp.ones((2, 3)):\n{arr_unos}")

# np.linspace(): ¡Muy útil! Devuelve números 'linealmente' espaciados.
# (inicio, fin_incluido, numero_de_puntos)
arr_lineal = np.linspace(0, 100, 5) # 5 puntos entre 0 y 100
print(f"\nnp.linspace(0, 100, 5):\n{arr_lineal}")

# np.random.randint(): Genera enteros aleatorios
# (valor_min, valor_max_no_incluido, forma)
np.random.seed(42) # Usamos una 'semilla' para que todos tengamos los mismos resultados
arr_random = np.random.randint(10, 100, (3, 5))
print(f"\nnp.random.randint(10, 100, (3, 5)):\n{arr_random}")

np.arange(0, 10, 2):
[0 2 4 6 8]

np.zeros((3, 4)):
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]]

np.linspace(0, 100, 5):
[  0.  25.  50.  75. 100.]

np.random.randint(10, 100, (3, 5)):
[[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]]


In [ ]:
# --- Concepto Base: Slicing 1D ---
arr_1d = np.arange(10, 20) # [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
print(f"Array 1D:\n{arr_1d}")

# Primer elemento
print(f"arr_1d[0]: {arr_1d[0]}") # 10

# Elementos del índice 2 al 5 (sin incluir el 5)
print(f"arr_1d[2:5]: {arr_1d[2:5]}") # [12, 13, 14]

# --- Concepto Base: Slicing 2D (LA CLAVE) ---
# Usaremos nuestro array aleatorio de antes
# [[83, 99, 88, 80, 26],
#  [91, 74, 34, 91, 39],
#  [60, 22, 5, 81, 71]]
print(f"\nArray 2D:\n{arr_random}")

# Sintaxis: array[fila, columna]

# 1. Obtener un solo elemento (Fila 1, Columna 2)
# (Recordar: el índice empieza en 0)
elem = arr_random[1, 2] # 34
print(f"\nElemento [1, 2]: {elem}")

# 2. Obtener una FILA completa (Fila 0)
# Usamos ':' para decir "todas las columnas"
fila = arr_random[0, :]
print(f"Fila [0, :]: {fila}")

# 3. Obtener una COLUMNA completa (Columna 1)
# Usamos ':' para decir "todas las filas"
col = arr_random[:, 1]
print(f"Columna [:, 1]: {col}")

# 4. Obtener un SUB-BLOQUE
# Filas de 0 a 2 (sin incluir 2) y Columnas de 1 a 4 (sin incluir 4)
# Es decir, filas [0, 1] y columnas [1, 2, 3]
sub_bloque = arr_random[0:2, 1:4]
print(f"Bloque [0:2, 1:4]:\n{sub_bloque}")

Array 1D:
[10 11 12 13 14 15 16 17 18 19]
arr_1d[0]: 10
arr_1d[2:5]: [12 13 14]

Array 2D:
[[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]]

Elemento [1, 2]: 84
Fila [0, :]: [61 24 81 70 30]
Columna [:, 1]: [24 96 12]
Bloque [0:2, 1:4]:
[[24 81 70]
 [96 84 84]]


In [ ]:
# --- Concepto Base: Operaciones vectorizadas ---
arr = np.array([1, 2, 3, 4])
print(f"Array original: {arr}")
print(f"arr + 10: {arr + 10}")
print(f"arr * 5: {arr * 5}")

# --- Concepto Base: Funciones Universales (UFuncs) ---
# Son funciones de NumPy que se aplican elemento a elemento
arr_float = np.array([1.0, 4.0, 9.0, 16.0])

# Raíz cuadrada de cada elemento
print(f"\nRaíz cuadrada (np.sqrt): {np.sqrt(arr_float)}")

# Logaritmo de cada elemento
print(f"Logaritmo (np.log): {np.log(arr_float)}")

Array original: [1 2 3 4]
arr + 10: [11 12 13 14]
arr * 5: [ 5 10 15 20]

Raíz cuadrada (np.sqrt): [1. 2. 3. 4.]
Logaritmo (np.log): [0.         1.38629436 2.19722458 2.77258872]


In [ ]:
# Usaremos nuestro array aleatorio de antes
print(f"Array 2D:\n{arr_random}")

# --- Paso 1: Crear la "Máscara" (Mask) ---
# Una máscara es un array de Booleans (True/False)
# Pregunta: ¿Qué elementos son mayores a 80?
mascara = arr_random > 80
print(f"\nMáscara (> 80):\n{mascara}")

# --- Paso 2: Aplicar la Máscara ---
# Le pasamos la máscara al array
# NumPy nos devolverá SOLO los elementos donde la máscara tenía un True
# OJO: Devuelve un array 1D
filtrados = arr_random[mascara]
print(f"\nValores filtrados (> 80):\n{filtrados}")

# También se puede hacer en una línea (muy común)
print(f"Valores < 40: {arr_random[arr_random < 40]}")

Array 2D:
[[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]]

Máscara (> 80):
[[False False  True False False]
 [ True  True  True  True  True]
 [False False False False False]]

Valores filtrados (> 80):
[81 92 96 84 84 97]
Valores < 40: [24 30 33 12 31 11]


In [ ]:
# --- Concepto Base: Agregación total ---
print(f"Array 2D:\n{arr_random}")

print(f"\nSuma total: {arr_random.sum()}")
print(f"Promedio total: {arr_random.mean()}")
print(f"Valor máximo: {arr_random.max()}")
print(f"Valor mínimo: {arr_random.min()}")

# --- Concepto Base: Agregación por Eje (axis) ---
# Esto es clave para el análisis
# axis=0 -> Colapsar verticalmente (operar sobre las COLUMNAS)
# axis=1 -> Colapsar horizontalmente (operar sobre las FILAS)

# Suma de cada COLUMNA
suma_cols = arr_random.sum(axis=0)
print(f"\nSuma de cada columna (axis=0): {suma_cols}")

# Promedio de cada FILA
prom_filas = arr_random.mean(axis=1)
print(f"\nPromedio de cada fila (axis=1): {prom_filas}")

Array 2D:
[[61 24 81 70 30]
 [92 96 84 84 97]
 [33 12 31 62 11]]

Suma total: 868
Promedio total: 57.86666666666667
Valor máximo: 97
Valor mínimo: 11

Suma de cada columna (axis=0): [186 132 196 216 138]

Promedio de cada fila (axis=1): [53.2 90.6 29.8]
